export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Header from '@/components/header/header';
import '../../styles/styles.css';
import * as BackgroundImg from '../../public/backgroud/background.jpg'

export default function RootLayout({ children }) {
  console.log( BackgroundImg)
 return (
    <html lang="en">
      <body style={{backgroundImage: `url(${BackgroundImg.src})`, backgroundSize: 'cover', backgroundPosition: 'center', height: '100vh'}}>
        <div >
          <Header/>
          {children}
        </div>
      </body>
    </html>
  )
}
